// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdx64vvl_h6UywUfEq-TEI3xudD1EH0q4',
    appId: '1:709127213804:web:9123b1be5137cd5bbccbc9',
    messagingSenderId: '709127213804',
    projectId: 'instreal-b2e86',
    authDomain: 'instreal-b2e86.firebaseapp.com',
    storageBucket: 'instreal-b2e86.appspot.com',
    measurementId: 'G-9KBRG67077',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMHnDaietKPAEIvSiyiJrBJHTVHF1Fl4',
    appId: '1:709127213804:android:3b3bdc457272e324bccbc9',
    messagingSenderId: '709127213804',
    projectId: 'instreal-b2e86',
    storageBucket: 'instreal-b2e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZYk3S44oGrCaENIc9sdxOODUSbFntUzE',
    appId: '1:709127213804:ios:729de64f7020588bbccbc9',
    messagingSenderId: '709127213804',
    projectId: 'instreal-b2e86',
    storageBucket: 'instreal-b2e86.appspot.com',
    iosClientId: '709127213804-c6nfp4ajj1besooa7pq093tmpvru34jo.apps.googleusercontent.com',
    iosBundleId: 'dev.fluttermtl.instreal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZYk3S44oGrCaENIc9sdxOODUSbFntUzE',
    appId: '1:709127213804:ios:73067d4cd18deeafbccbc9',
    messagingSenderId: '709127213804',
    projectId: 'instreal-b2e86',
    storageBucket: 'instreal-b2e86.appspot.com',
    iosClientId: '709127213804-7ot40m98th2om425khqehesg349cu59f.apps.googleusercontent.com',
    iosBundleId: 'dev.fluttermtl.instreal.RunnerTests',
  );
}
